name: Deploy to WordPress.org

on:
  push:
    tags:
      - "*"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Deploy plugin to WordPress.org
        uses: 10up/action-wordpress-plugin-deploy@stable
        with:
          slug: dashclean
          svn_username: ${{ secrets.SVN_USERNAME }}
          svn_password: ${{ secrets.SVN_PASSWORD }}
